// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw-KZIDo490f0pW8I2Cr-YybZP6mNwtrI',
    appId: '1:50155577219:android:1a1fd5526d6c5dce2ae0b6',
    messagingSenderId: '50155577219',
    projectId: 'newstud',
    storageBucket: 'newstud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzkGZ87ixUsPte0FKuompXJNTWgN6G610',
    appId: '1:50155577219:ios:8a6c6b473c6e1ff92ae0b6',
    messagingSenderId: '50155577219',
    projectId: 'newstud',
    storageBucket: 'newstud.appspot.com',
    iosClientId: '50155577219-0i973euv9pmsbsndcvca91b2vcnqe7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newstudapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzkGZ87ixUsPte0FKuompXJNTWgN6G610',
    appId: '1:50155577219:ios:8a6c6b473c6e1ff92ae0b6',
    messagingSenderId: '50155577219',
    projectId: 'newstud',
    storageBucket: 'newstud.appspot.com',
    iosClientId: '50155577219-0i973euv9pmsbsndcvca91b2vcnqe7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.newstudapp', 
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw-KZIDo490f0pW8I2Cr-YybZP6mNwtrI',
    appId: '1:50155577219:web:1a1fd5526d6c5dce2ae0b6',
    messagingSenderId: '50155577219',
    projectId: 'newstud',
    authDomain: 'newstud.firebaseapp.com',
    storageBucket: 'newstud.appspot.com',
  );
}
